### PR TITLE
[fix] correctly merge env-specific configs

### LINKED ISSUE #102: Environment config not loaded
When environment is set to `production`, trails doesn't override default config by `config/env/production.js` file. 

For example trailpack-repl is not disable, I can see debug logs and I put some config for trailpack-gulp to build assets in production mode but it take the dev tasks.

The command to test the issue
```
$ NODE_ENV=production node server.js
```

Maybe something wrong around here https://github.com/trailsjs/trailpack/blob/master/index.js#L43 methods return merge config but it was not used ?

### LINKED ISSUE #147: validate that config.env cannot itself contain an env property
#### Issue Description
Trails behavior for when the user sets an `env` property inside the environment-specifc configs (in config/env/<something>) is undefined. The config validator should explicitly disallow this.

#### Environment
- node version: all
- trails version: 1.0-beta
- operating system: all

### PR DESCRIPTION
**Pull request by tjwebb**
#### Description
fix merging environment-specific configs. (in config/env)

#### Issues
- resolves #102
- resolves #147

### CODE REVIEW

File: lib/trails.js [hunk 1]
```diff
@@ -1,44 +1,63 @@
...
 
-    if (!config.main.paths.temp) {
-      config.main.paths.temp = path.resolve(process.cwd(), '.tmp')
+    // merge remaining environment-specific config properties
+    return Object.assign({ }, config, envConfig, configTemplate)
+  },
+
+  validateConfig (config) {
+    if (lib.Trails.hasNestedEnv(config)) {
+      console.error('config.env' + process.env.NODE_ENV, 'contains the "env" property')
```
Comment (tjwebb) [inline lib/trails.js]: This error message is actually not accurate
