### PR TITLE
Fix merge environment config 

### LINKED ISSUE #200: Environment config problem
#### Issue Description
If I put this under `config/env/production.js` : 

```
const winston = require('winston')

module.exports = {

  trailpack: {
    disabled: [
      'repl'
    ]
  },
  database: {
    /**
     * Define the database stores. A store is typically a single database.
     *
     * Use the SQLite3 by default for development purposes.
     *
     * Set production connection info in config/env/production.js
     */
    stores: {

      /**
       * Define a store called "local" which uses SQLite3 to persist data.
       */
      sqlitedev: {
        adapter: require('waterline-sqlite3'),
        migrate: 'safe'
      }
    },

    models: {
      defaultStore: 'sqlitedev',
      migrate: 'safe'
    }
  },

  web: {
    port: 8080
  },

  log: {
    logger: new winston.Logger({
      level: 'info',
      exitOnError: false,
      transports: [
        new winston.transports.Console({
          timestamp: true
        }),
        new winston.transports.File({
          name: 'info-file',
          level: 'info',
          filename: 'trails-info.log',
          timestamp: true
        }),
        new winston.transports.File({
          name: 'error-file',
          level: 'error',
          filename: 'trails-error.log',
          timestamp: true
        })
      ]
    })
  }
}
```

They are 2 problem : 

- Trailpack repl was not disable, `trailpack` field config seems ignored
- Config are not override the default `config/*`, it's replace it, this means I loose every config I put for `config.web` witch is for dev and prod, all I want to do is change the port number but everything else is lost.

#### Environment
- node version: all
- trails version: 1.0.0
- operating system: all

### PR DESCRIPTION
**Pull request by jaumard**
#### Description
Merge environment config to merge only `log` and `main` and leave trailpack environnement config to `trailpack` like we talk about https://github.com/trailsjs/trails/issues/200 with @tjwebb 

Next I will make a PR to `trailpack` to merge environment config correctly (because this PR alone is not enough to fix the issue.

This PR is only about merge environment config, not about disabling trailpacks by config

#### Issues
- resolves #200

### CODE REVIEW

**Comment by jaumard** [comment]
Trailpack PR is here https://github.com/trailsjs/trailpack/pull/32

File: lib/trails.js [hunk 1]
```diff
@@ -44,10 +44,8 @@ module.exports = {
     // merge application log
     Object.assign(configTemplate.log, config.log, envConfig.log)
 
-    delete config.env
-
     // merge remaining environment-specific config properties
-    return Object.assign({ }, config, envConfig, configTemplate)
+    return Object.assign({ }, config, configTemplate)
```
Comment (tjwebb) [inline lib/trails.js]: thanks. I don't know what I was thinking here.
